<<<<<<< HEAD
size: [64, 64]
n1: 16
conv1: [5, 5]
n2: 32
conv2: [5, 5]
n3: 64
opt: "Adam" # SGD, RMSprop, Adam
lr: 0.001
bs: 10
=======
size: [128, 128]
n1: 64
conv1: [3, 3]
n2: 32
conv2: [3, 3]
n3: 16
opt: "SGD" # SGD, RMSprop, Adam
lr: 0.01
bs: 15
>>>>>>> 4dbc180dc42f2fe19474ec2aab95df92bfaf9977
n_epochs: 10