size: [32, 32]

model:
  n1: 32
  conv1: [3, 3]
  n2: 64
  conv2: [3, 3]
  n3: 128
  conv3: [3, 3]
  n4: 256
  conv4: [3, 3]
  n5: 512
  opt: "Adam" # SGD, RMSprop, Adam
  lr: 0.001
  bs: 10
  n_epochs: 10

paths:
  path_big: C:\Users\Debora\Desktop\AI\Teme_suplimentare\retele_convolutionale\covid_dataset
  path_small: C:\Users\Debora\Desktop\AI\AI-intro\5_Retele_Neurale\covid_dataset

img_gen:
  rescale: 0.0039
  rotation_range: 40
  width_shift_range: 0.2
  height_shift_range: 0.2
  shear_range: 0.2
  zoom_range: 0.2
#  horizontal_flip: False
#  brightness_range: [10, 10]

